spring:
  datasource:
    url: jdbc:mariadb://localhost:33062/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: s5554549
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: 12345
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            
logging:
  level:
    root: info
    
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

